name: e-commerce

services:
  db: 
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432" #host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379" #host:container
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: